### PR TITLE
Functioning Frontend

### PR DESCRIPTION
**Pull request by gnumonik**
I believe I've fixed the TX submission bug - each of the endpoints is working (though it takes a while to confirm tx submission). 

Could you confirm that it works for you as well @zmrocze ?

NOTE: For the `Script` endpoints, you have to wait until you get the `alert` popup after `Lock`-ing funds before you can attempt to `Unlock`. Also, it might take a minute or two (literally) to confirm the `Unlock` transaction - but it should confirm eventually and show up in your wallet.

### CODE REVIEW

**Comment by zmrocze** [comment]
So in the end this was the problem, right?
>For the Script endpoints, you have to wait until you get the alert popup after Lock-ing funds before you can attempt to Unlock.

**Comment by gnumonik** [comment]
> So in the end this was the problem, right?
> 
> > For the Script endpoints, you have to wait until you get the alert popup after Lock-ing funds before you can attempt to Unlock.

For every endpoint except the Unlock endpoint, yes. For the Unlock endpoint, I misunderstood (i.e. guessed wrong because I couldn't find an example and it wasn't documented anywhere) how to deconstruct a PS `Maybe` value in JS, which was obscuring another mistake (I forgot a `MustSpendAtLeast` constraint in the PureScript API - the `Maybe` thing was causing an UncaughtTypeError that was hiding that problem).

**Comment by zmrocze** [comment]
Moved to #16

**Comment by zmrocze** [comment]
Moved to #16

**Pull request closed without merging**
